<div class="container" id="main-content">
	<h2>Üdvözöljük az oldalunkon</h2>
	<h3>Névadónk: I. István magyar király</h3>
	<p> I. (Szent) István király – születési nevén Vajk (Esztergom, 970-980 – 1038. augusztus 15.) 
Az első magyar király.</p></br>

<p>Uralkodása alatt a magyar törzsek szövetségéből kialakult fejedelemséget egységes, keresztény magyar királysággá alakította át. Ez 1028-tól az egész Kárpát-medencére kiterjedt. Az általa meghirdetett új politikai irányvonalnak ellenszegülő törzseket fegyverrel vagy békés úton behódoltatta, a lázadásokat leverte. Az ezeréves magyar törvénytár az általa alkotott törvényekkel kezdődik. Az államszervezet kiépítésével párhuzamosan megszervezte a magyar keresztény egyházat, ezért ő és utódai viselhették az apostoli király címet. Magyarországon minden év augusztus 20-án I. István király szentté avatásának napját ünnepeljük.
</p>
 


<h4>Nevének eredete </h4>
<p>
Születésekor a türk eredetű pogány Vajk nevet kapta, mivel a mainzi érsek által a magyarok számára küldött térítő, Brúnó püspök ekkor már nem tartózkodott a Kárpát-medencében. László Gyula történész szerint török nyelvű volt Vajk, a név feltehetően a török hős, vezér jelentésű szóból származik. Ilyen módon a török bej szó rokona. Az eredetileg gazdag jelentésű szó a magyarban (bő) és a törökben is nemzetségfő jelentésűvé vált.
</p>
<h4>Megkeresztelése</h4>
<p>
Apját, Gézát és családját (pl. öccsét, Mihályt) az ő kérésére I. Ottó német-római császár által 972-ben Magyarországra küldött Sankt Gallen-i Bruno keresztelte meg. Géza a keresztségben az István nevet kapta. Azon vita folyik, hogy Vajk/István ekkor élt-e már. Ennek az elméletnek két tény is ellentmond. Az egyik az, hogy egyes források 975-re teszik Vajk születését, a másik pedig az, hogy ha ilyen korán áttért volna a keresztény hitre, nyugaton nem Vajkként ismerték volna még sokáig.
Szent Adalbert prágai püspök életrajza szerint ő gondoskodott István keresztény szellemű taníttatásáról, és ő volt az is, aki megkeresztelte valószínűleg 994. és 996. között. Az a tény ugyanis, hogy német földön még évtizedekkel később is Vajkként beszéltek róla, ezt a későbbi időpontot erősíti. Emellett több forrás, kútfők, a legkorábbi István-legenda, illetve egy 14. századi krónika is említi Vajk keresztelőjének nevét, Adalbertet. Névadója az első keresztény vértanú, István volt, vagy éppen Géza keresztségben kapott nevét örökölte (Sztephanosz, magyarul István). Adalbert szerepének viszont ellentmond, hogy ő ugyan 983-tól volt prágai püspök, de ezután egy ideig ott is tartózkodott, majd 989–994-ig Rómában élt az aventinusi Szent Elek és Bonifác apátságban. 994-ben visszavitték Prágába, majd egy idő után Magyarországon is tartózkodva 995-ben visszatért Rómába.
Így tehát nem tudjuk, ki és mikor keresztelte meg Istvánt, és talán soha nem is tudjuk meg, de sem Bruno sem Adalbert nem tűnik valószínűnek.
A képes krónika szerint az Olaszországból származott Deodatus gróf volt Szent István keresztapja, akit a herceg Tatának hívott (a hagyomány szerint a Tata város róla kapta nevét).
</p>
<h4>Házassága </h4>
<p>
Adalbertnek esetleg szerepe volt házasságának létrejöttében. István 996-ban vette feleségül II. Henrik bajor herceg leányát, a későbbi II. Szent Henrik német császár testvérét, Gizellát. Bajor hagyomány szerint az esküvő Scheyern bencés apátságban köttetett. Német krónikások feljegyezték, hogy a bajorok a házasságtól a kereszténység gyors terjedését várták, és ennek érdekében minden segítséget igyekeztek Istvánnak megadni. Gizellával együtt jelentős számban érkeztek bajor papok, lovagok és mesteremberek az országba.
</p>
<h4>Fejedelemsége</h4>
<p>
István atyja életében a nyitrai dukátus (lásd Nyitrai Fejedelemség és Hercegség) ura volt, majd 997-ben, Géza fejedelem halála után követte őt a fejedelmi székben. Géza azért, hogy fia számára biztosítsa a trónt halála után, megeskette a főurakat, hogy fiát támogatják.
Azonban mikor Géza meghalt, Koppány bejelentette igényét a fejedelmi trónra. Koppány az apja, Tar Szerénd és Géza által kötött szerződés értelmében a Balatontól délre eső területek ura volt. Igényét a trónra a szeniorátus és a levirátus – István megözvegyült édesanyját, Saroltot feleségül kívánta venni – jogára való hivatkozással indokolta. Koppány mellé sorakoztak fel a régi rend és a törzsi szabadság hívei, akikben az ellenállást az is fokozhatta, hogy István körül nagy számban csoportosultak idegen nemzetiségűek, főleg németek.
István hadait is német hadvezérek (Hont (Hunt), Paznan (Pazman), Vecelin, Orci) irányították és az sem kizárt, hogy III. Ottó német-római császár is küldött seregeket István segítésére. A döntő ütközetre Veszprém közelében került sor, ahol István megverte a pogány seregeket; a csatában Koppány is életét vesztette, Vecelin ölte meg. István Koppány testét felnégyeltette és testrészeit hónapokig kifüggesztve tartották az ország négy legfontosabb várának kapuja felett – Győrben, Veszprémben, Esztergomban és Gyulafehérváron – jelezve, hogy mi vár az uralkodónak nem engedelmeskedőkre. Ezzel István ősi emberi és magyar törvényt szegett meg, amely szerint a halottakat el kell temetni. Tette elrettentésre szolgált, kegyetlen bánásmóddal fenyegetve azokat, akik nem engedelmeskednek neki és papjainak.
István és Koppány harcában nemcsak az forgott kockán, hogy ki lesz a magyar nép uralkodója, hanem a keleti és nyugati orientáció kérdése. Koppánnyal – aki egyes források szerint bizánci rítus szerint megkeresztelkedett – a bizánci politikai befolyás erősödött volna, míg István győzelmével a német irányvonal nyert teret. A Kárpát-medence geopolitikai helyzete folytán a kor két nagyhatalma közé ékelődve irányt kellett választani. Közkeletű téves magyarázat szerint az állam léte, vagy a magyarság léte forgott kockán ezen, azonban ez a kérdés a történelmi mi lett volna, ha... kategóriája. Koppány esetleges győzelmével éppolyan státuszú és helyzetű magyar fejedelemség alakult volna ki, vélhetően bizánci irányvonallal, mint az erdőelvei fejedelemség, jövendő sorsa azonban nem meghatározható. A Koppány által vezetett magyar fejedelemség éppúgy az ő további személyes bel- és külpolitikájának sikerétől függött volna, ahogyan azt az István vezette állam esetében is látjuk, amely azonban a környező országokhoz hasonlóan keresztény állammá vált.
</p>
<h4>Koronázása</h4>
<p>
Ezután István el akarta magát ismertetni az ország határain túl is, mint Isten kegyelméből uralkodó királyt, aki nem csak a turulmadár jóslata következtében gyakorolja a hatalmat népe felett, ami csak a pogány uralmi megerősítést adhatta István számára. Ennek érdekében 999-ben Asztrik pannonhalmi apátot küldte Rómába, hogy az ott időző II. Ottóval tárgyaljon. A kortárs Theotmár merseburgi püspök legalábbis így tudta. István szentté avatása előtt a Kisebb legenda már arról tudósít, hogy II. Szilveszter pápa volt a követjárás célja, akitől koronát és apostoli áldást nyert, és Magyarország belépett az európai keresztény nemzetek sorába, ezen belül is a nyugati kereszténység felé orientálódott. A pápai levéltár mindenesetre nem tudott erről, és jóval későbbiek az első lateráni említései. II. Szilveszter – mint Ottó kreációja – egyébként sem léphetett ilyen jelentőségű ügyben önállóan.
Mindezek mellett megtartotta függetlenségét, és nem lett a császár hűbérese, bár a korona – amely az általános vélekedés szerint nem azonos a ma Szent Korona néven ismert uralkodói jelvénnyel – elfogadása az európai hatalmi rendszerbe tagozódás jelképe volt. Ezzel megalakult a keresztény, független Magyar Királyság. Ekkor már állt a veszprémi püspökség és a győrinek is megvetették az alapjait.
A koronázásra időpontjául a krónikák és az évkönyvek hol az 1000., hol az 1001. évet adják meg. A pécsi püspökség alapítólevelének dátumából kiderül, hogy 1009. augusztus 23-án István király uralkodásának 9. évében volt, a koronázás tehát 1000. augusztus 23. és 1001. augusztus 22. között történt. A 11-12. században vezetett királylajstrom szerint, amely tartalmazta István király uralkodásának hosszát év-hó-nap-ban megadva, a koronázás és a halál között 7 hónap 14 nap telt el. Halála augusztus 15-re esett, így a koronázás dátumául 1001. január 1. adódik. Ez összhangban lenne az ezredforduló világvégevárásával, amely nyilvánvalóan nem következett be január 1. eljövetelével és így megeshetett a koronázás. Ez összhangban van azzal a ténnyel is, hogy az István koronázását támogató III. Ottó császár 1000. augusztus 14. – 1001. február 15-ig Rómában tartózkodott.
</p>

</div>